# Generated by Django 4.2.8 on 2023-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_refrigeratorrepairservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('specialization', models.CharField(max_length=25, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастеры',
            },
        ),
    ]
