# Generated by Django 4.2.8 on 2023-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_appliance_delete_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('refrigerator', 'Ремонт холодильников'), ('tv', 'Ремонт телевизоров'), ('washing_machine', 'Ремонт стиральных машин'), ('small_appliance', 'Ремонт малой бытовой техники')], max_length=20, verbose_name='Тип услуги')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
