# Generated by Django 4.2.8 on 2023-12-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appliance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='RefrigeratorRepairService',
        ),
        migrations.DeleteModel(
            name='SmallApplianceRepairService',
        ),
        migrations.DeleteModel(
            name='TVRepairService',
        ),
        migrations.DeleteModel(
            name='WashingMachineRepairService',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
