# Generated by Django 4.2.8 on 2023-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_order_appliance_remove_order_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('refrigerator', 'Ремонт холодильников'), ('tv', 'Ремонт телевизоров'), ('washing_machine', 'Ремонт стиральных машин'), ('small_appliance', 'Ремонт малой бытовой техники')], max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='appliance',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип техники'),
        ),
    ]
