# Generated by Django 4.2.8 on 2023-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_order_options_remove_order_appliance_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('in_progress', 'В работе'), ('completed', 'Выполнено')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
