# Generated by Django 4.2.8 on 2023-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('specialization', models.CharField(choices=[('refrigerator', 'Ремонт холодильников'), ('tv', 'Ремонт телевизоров'), ('washing_machine', 'Ремонт стиральных машин'), ('small_appliance', 'Ремонт малой бытовой техники')], max_length=100, verbose_name='Специализация')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
