# Generated by Django 4.2.8 on 2023-12-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.master', verbose_name='Мастер'),
        ),
    ]
