# Generated by Django 5.1.3 on 2024-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0014_order_master"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appliance",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="order",
            name="master",
        ),
        migrations.RemoveField(
            model_name="order",
            name="service",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.DeleteModel(
            name="Master",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
