# Generated by Django 5.1.3 on 2024-12-04 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "authapp",
            "0015_delete_appliance_delete_contact_remove_order_master_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Тип техники")),
                ("brand", models.CharField(max_length=30, verbose_name="Марка")),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                (
                    "serial_number",
                    models.CharField(max_length=50, verbose_name="Серийный номер"),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техники",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "phonenumber",
                    models.CharField(max_length=12, verbose_name="Номер телефона"),
                ),
                ("description", models.TextField(verbose_name="Описание проблемы")),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("refrigerator", "Ремонт холодильников"),
                            ("tv", "Ремонт телевизоров"),
                            ("washing_machine", "Ремонт стиральных машин"),
                            ("small_appliance", "Ремонт малой бытовой техники"),
                        ],
                        max_length=100,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(verbose_name="Опыт работы (лет)"),
                ),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("refrigerator", "Ремонт холодильников"),
                            ("tv", "Ремонт телевизоров"),
                            ("washing_machine", "Ремонт стиральных машин"),
                            ("small_appliance", "Ремонт малой бытовой техники"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "В обработке"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнено"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authapp.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authapp.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
