# Generated by Django 5.1.3 on 2024-12-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0018_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="date",
            field=models.DateField(null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="training",
            name="time_end",
            field=models.TimeField(null=True, verbose_name="Время окончания"),
        ),
        migrations.AlterField(
            model_name="training",
            name="time_start",
            field=models.TimeField(null=True, verbose_name="Время начала"),
        ),
    ]
