# Generated by Django 5.1.3 on 2024-12-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0019_training_date_alter_training_time_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainer",
            old_name="dance_style",
            new_name="specialization",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="dance_style",
            new_name="specialization",
        ),
    ]
