# Generated by Django 5.1.3 on 2024-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0020_rename_dance_style_trainer_specialization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="gym_number",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Номер зала"
            ),
        ),
    ]
