# Generated by Django 5.1.3 on 2024-12-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0021_alter_training_gym_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authapp.trainer",
                verbose_name="Тренер",
            ),
        ),
    ]
