# Generated by Django 5.1.3 on 2024-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0022_alter_training_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("active", "Активный"), ("inactive", "Не активный")],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
