# Generated by Django 5.1.3 on 2024-12-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0024_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
