# Generated by Django 5.1.3 on 2024-12-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0025_delete_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
